### ISSUE TITLE
Changing tab when going up or down.

### ISSUE THREAD

**Issue by Peeeaje** [hiasr/vim-zellij-navigator#3]
Hello. Is it intended behavior that going up or down changes tab?

For me it is natural only left/right move across tabs and up/down does not, so if you changed the default behavior or added config for that it would be pretty cool. :)

**Comment by hiasr** [comment]
I assume you build from source, since the tab change is not on a release yet :smiley:. I just pushed a commit fixing this, [apparently `move_focus_or_tab` is only designed for left/right. ](https://zellij.dev/documentation/keybindings-possible-actions#movefocusortab). If you build again, it should be fixed!

**Comment by Peeeaje** [comment]
@hiasr Yep I wanted the feature I built from the source. 

Thanks for pretty fast response!!
